'use client';

import { CheckCircle2, FileText } from 'lucide-react';
import { useTranslations } from 'next-intl';

interface SummaryBlockProps {
  content: string;
  data?: {
    iterations?: number;
    testCasesCreated?: number;
    testCases?: Array<{ id: string; name: string }>;
  };
}

export function SummaryBlock({ content, data }: SummaryBlockProps) {
  const t = useTranslations('aiGenerate');
  return (
    <div className="rounded-lg border border-primary bg-primary/10 p-4 my-2">
      <div className="flex items-start gap-3">
        <div className="w-8 h-8 rounded-lg bg-primary/20 flex items-center justify-center flex-shrink-0">
          <CheckCircle2 className="w-5 h-5 text-primary" />
        </div>

        <div className="flex-1">
          <h4 className="font-semibold text-sm text-foreground mb-2">
            ✅ {content}
          </h4>

          {data && (
            <div className="space-y-2 text-sm text-foreground">
              {data.testCasesCreated !== undefined && data.testCasesCreated > 0 && (
                <>
                  <p className="font-medium">
                    {t('testCasesGenerated')} {data.testCasesCreated} {t('testCases')}
                  </p>
                  {data.testCases && data.testCases.length > 0 && (
                    <ul className="space-y-1 pl-4">
                      {data.testCases.map((testCase) => (
                        <li key={testCase.id} className="flex items-start gap-2">
                          <FileText className="w-3 h-3 mt-0.5 flex-shrink-0" />
                          <span className="text-xs">{testCase.name}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </>
              )}

              <div className="pt-2 border-t border-border text-xs space-y-1 text-muted-foreground">
                <p>✓ {t('autoAddedAssertions')}</p>
                <p>✓ {t('autoAddedStatusCheck')}</p>
                {data.testCasesCreated && data.testCasesCreated > 1 && (
                  <p>✓ {t('autoGeneratedScenarios')}</p>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

